version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    # restart: always
    ports:
      - 27017:27017
  app:
    container_name: app
    image: us-central1-docker.pkg.dev/${GOOGLE_PROJECT_ID}/hello-repo/flight-scraper:v1
    restart: always
    build: .
    env_file: .env
    ports:
      - 8080:8080
    external_links:
      - mongo
    depends_on:
      - mongo
