# 2 stage build
# https://cloudnweb.dev/2019/09/building-a-production-ready-node-js-app-with-typescript-and-docker/
# FROM node:14-slim as BUILD_IMAGE
# WORKDIR /usr
# COPY package.json ./
# COPY tsconfig.json ./
# COPY src ./src
# RUN ls -a
# RUN npm install
# RUN npm run build

FROM ghcr.io/puppeteer/puppeteer:latest

WORKDIR /home/pptruser
COPY package.json .
COPY tsconfig.json ./
RUN npm install --loglevel=warn;
USER node

COPY . ./
RUN ls -a
# RUN npm install
# RUN npm run build

EXPOSE 8080

# ENTRYPOINT ["dumb-init", "--"]
# TODO Add client start
CMD ["npm", "run", "dev:start"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
