version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
  app:
    container_name: app
    external_links:
      - mongo
    depends_on:
      - mongo
    cap_add: 
      - SYS_ADMIN
    environment:
      - PORT=${PORT}
      - MONGODB_URI=#{MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - APPLITOOLS_API_KEY=${APPLITOOLS_API_KEY}
      - TWO_CAPTCHA_KEY=${TWO_CAPTCHA_KEY}
      - LOG_LEVEL=${LOG_LEVEL}